### ISSUE TITLE
Remote loosing connection to NZ8 after latest update

### ISSUE THREAD

**Issue by roninf** [iloveicedgreentea/jvc_homeassistant#42] opened 2024-02-20 09:25 UTC
Hi all,

since the latest update the integration that has been setup through the HA UI seems to loose connection to my NZ8. (setup using yaml is not accepted anymore?)
All sensors showing unavailable and the remote is not able to turn on/off the device. Its only working after the initial setup (for a few seconds). At least its seems so...

Any Idea what i could/should check ?

BR

**Comment by iloveicedgreentea** [comment] 2024-02-20 14:47
first confirm you are putting in the right info

entity name (same as your old entity name like nz8 or whatever)
host IP
password
timeout seconds

If that doesnt work turn on debug logs and send me that
```
  default: warning
  logs:
    homeassistant.config_entries: debug
    custom_components.jvc_projectors: debug
```

**Comment by roninf** [comment] 2024-02-20 15:17
Entity names are correct. :)
I think it kind of solved by itself, but i guess it takes longer than usual to show/provide updates on states of the different sensors.

**Comment by iloveicedgreentea** [comment] 2024-02-21 03:03
4.2.1 should hopefully fix any outstanding issues. If you have any more feel free to reopen this

**Comment by roninf** [comment] 2024-02-21 19:28
Thanks very much for the prompt response and your work on this integration!! Running on 4.2.0 i guess.

**Comment by roninf** [comment] 2024-03-08 07:56
I still have massive issues using the integration not quite sure if these are the correct logs:

`2024-02-26 16:02:34.697 WARNING (MainThread) [homeassistant.helpers.entity] Update of remote.theater_projector is taking over 10 seconds
2024-02-26 16:02:54.695 WARNING (MainThread) [homeassistant.components.remote] Updating jvc_projectors remote took longer than the scheduled update interval 0:00:30
2024-02-26 16:03:24.697 WARNING (MainThread) [homeassistant.components.remote] Updating jvc_projectors remote took longer than the scheduled update interval 0:00:30
2024-02-26 16:03:33.789 ERROR (MainThread) [JVC_projectors] Got a blank msg
2024-02-26 16:03:33.890 ERROR (MainThread) [JVC_projectors] Got a blank msg
2024-02-26 16:03:34.071 ERROR (MainThread) [custom_components.jvc_projectors.remote] Error getting attribute: Connection lost -- Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 389, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/jvc_projectors/remote.py", line 251, in update_worker
    value = await getter()
            ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/jvc_projector.py", line 440, in get_hdr_data
    return await self._get_attribute("hdr_data", ACKs.info_ack, HdrData)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/jvc_projector.py", line 314, in _get_attribute
    state, res = await self.commander.do_reference_op(command, ack)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 268, in do_reference_op
    msg, success = await self.send_command(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 82, in send_command
    return await self._do_command(send_command, ack, command_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 164, in _do_command
    raise ConnectionClosedError(err) from err
jvc_projector.error_classes.ConnectionClosedError: Connection lost
2024-02-26 16:03:54.701 ERROR (MainThread) [homeassistant.helpers.entity] Update for remote.theater_projector fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 377, in drain
    raise exc
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1061, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe`

**Comment by iloveicedgreentea** [comment] 2024-03-09 17:49
Can you try 4.2.3? You will have to show beta versions in hacs.

**Comment by roninf** [comment] 2024-03-09 18:53
I have used 4.2.3 now and it shows offline while the projector is running right now:

![grafik](https://github.com/iloveicedgreentea/jvc_homeassistant/assets/51538247/cfba6423-7890-4170-b5c9-14bb4c5c01d9)

**Comment by roninf** [comment] 2024-03-12 18:23
So it happened i was able to turn on the projector using the integration but afterwards the projector is kind of dead. Not reacting to any command neither using ip nor IR with the regular remote. While its still showing a picture you cant even turn it of. The only way is cutting power... weird.

**Comment by iloveicedgreentea** [comment] 2024-03-12 21:58
I am working on another rewrite to fix these issues. 2.4.3 has been stable for me but seems there are edge cases. Should be out this week or sooner

**Comment by roninf** [comment] 2024-03-13 19:18
Ok thanks very much, i ll take a look then.

**Comment by roninf** [comment] 2024-03-16 19:09
Right now i am on Beta 2.4.6 i guess and it seems that the remote can turn on the projector but does not get any feedback if the projector is on or not. So it shows offline while the projector is on.

Don`t know if its related but its shows a timeout now:

```
Logger: custom_components.jvc_projectors.remote
Quelle: custom_components/jvc_projectors/remote.py:116
Integration: JVC Projector ([Dokumentation](https://github.com/iloveicedgreentea/jvc_homeassistant))
Erstmals aufgetreten: 19:59:05 (1 Vorkommnisse)
Zuletzt protokolliert: 19:59:05
Timeout while trying to connect to 10.2.0.50
```

**Comment by iloveicedgreentea** [comment] 2024-03-17 02:06
please try 2.4.7 that should fix issues with attributes

**Comment by roninf** [comment] 2024-03-17 09:15
Will do so...

**Comment by roninf** [comment] 2024-03-17 09:16
Seems that it switches to online for a second, but its showing offline immediately again.

**Comment by iloveicedgreentea** [comment] 2024-03-20 03:06
how about 4.2.9? Just had to rewrite a lot more logic but it seems to be stable for me now

**Comment by roninf** [comment] 2024-03-20 06:39
I am at work right now, but i will update this afternoon and let you know.

**Comment by roninf** [comment] 2024-03-20 06:57
By the way not related to this issue but might be usefull: for the NZ series you can now (software version 3) adjust laserpower from 0 to 100 not only in low/mid/high. Your approach is still working though....

**Comment by iloveicedgreentea** [comment] 2024-03-20 13:54
yeah I implemented that a few version ago as laser_value I still have to do an overhaul of the readme

**Comment by iscofield** [comment] 2024-03-21 01:59
Having the same issue as this was working before the update and now for the life of me I can’t get it to connect to the projector at all. It always just says false with no updates even on 4.2.9. 

Did you have to do anything else to get it to work?

**Comment by roninf** [comment] 2024-03-21 07:35
No i have always been able to connect/configure (if i understood you issue correctly) the integration but it was not working anymore. Setup itself has more or less never been an issue for me. I have had issues that my projector kind of crashed hence not reacting to any command be it ip or ir. But that seem to be solved. 

You could try to deinstall the integration completely and check wether there are still files left. Reboot HA and start over.

**Comment by iscofield** [comment] 2024-03-21 12:50
I messed around with it more this morning and it can turn the projector on, but the problem is none of the attributes ever populate.  I had the projector up and running last night and was uninstalling / reinstalling and rebooting HA but it never populated.

Same thing again this morning.  I used the HA plugin to tun on the projector and 10 minutes later, the plugin still says the device is off, no attributes, etc.

<img width="598" alt="Screenshot 2024-03-21 at 7 43 04 AM" src="https://github.com/iloveicedgreentea/jvc_homeassistant/assets/9456295/24694dc8-c48d-442f-a766-feab1070ac99">

Obviously the plugin can connect to the device as it can turn it on and it says connection alive is true.  But for some reason, it's all the metadata that's broken?

**Comment by iscofield** [comment] 2024-03-22 01:24
Worked on this more tonight and seems to be working now?  After removing / reinstalling, using different entity names to ensure no older configuration was used, etc. I can turn it on, but the plug in immediately toggles off after turning the projector on.  Then a few seconds later, now it displays all the information and is now triggering my MadVR envy automations again.  Not sure what exactly did the trick but we're back in business!  Thanks for the plugin!

**Comment by roninf** [comment] 2024-03-22 12:09
Thats the same i described ealier on but i think one can live with it. Just did another test i turned on the projector using IR but the RemoteIntegration never reported the change its just stayed showing offline....

**Comment by iscofield** [comment] 2024-03-22 12:14
Hmm yes in my testing last night I was only doing it with the plugin but my normal setup is for my harmony remote to turn on the projector via IR. I’ll test that this morning to see if it’s the same for me. As that is what my issue was the first time is the projector was turned on via the harmony and the plugin never recognized it being on. If that’s the case, then it seems like the plugin only works if it has exclusive control and either the projector doesn’t report the status correctly depending on whether it’s controlled by IP or IR, or the plugin has some initialization logic that only fires when it sends the power on command vs just reporting what the projector is doing if it’s turned on via another source, which is my setup.

**Comment by iscofield** [comment] 2024-03-22 14:46
Yea....I spoke to soon.  Doesn't work if you power on the projector via IR.  So for some reason, the most recent updates (whenever it switched from YAML config to UI config) it no longer works if the plugin doesn't seemingly have complete control and initiates the power on.

**Comment by iloveicedgreentea** [comment] 2024-03-22 16:55
Are you using the latest beta version? It should detect if its on, regardless of how its turned on as long as the integration has a connection open

**Comment by iscofield** [comment] 2024-03-22 17:20
Yep, using 4.2.9.  That's what I see in HACS for the current version when I click "redownload".  I don't see a place on the actual integration page to check the installed version there, but I don't see why they'd be different.

**Comment by iloveicedgreentea** [comment] 2024-03-22 17:36
in the integration page you can enable debug logs turn that on, restart, and then send me logs of you trying to turn it on and stuff. I think the debug log should persist with reboots

also what does the connection_active attribute say

**Comment by iscofield** [comment] 2024-03-22 18:09
While the projector is off, the connection status is false.  If I turn on the projector via the IR remote or my Harmony, it stays as false and never switches.  If I turn on the projector via the plugin, then it will say true and everything will populate (after it sits for a bit, then says the remote is off, then comes back).

Will grab the debugs later today/tonight and send them over.

**Comment by iloveicedgreentea** [comment] 2024-03-23 01:08
If you open file editor and go to custom_components/jvc_projectors/manifest.json can you post that and remote.py?

I want to make sure you have the right files. I am not able to replicate these issues on the latest version

It will open a connection when HA starts and only close it if you disable the integration. Do you have the other official JVC integration installed?

**Comment by iscofield** [comment] 2024-03-23 01:14
I promise I'm not crazy, but now when trying to reproduce it with debug on, the plugin is now working and showing the correct power on state and triggering my other envy automations.  

Here's manifest.json
```
{
  "domain": "jvc_projectors",
  "name": "JVC Projector",
  "config_flow": true,
  "documentation": "https://github.com/iloveicedgreentea/jvc_homeassistant",
  "requirements": [
    "pyjvc==4.3.51"
  ],
  "ssdp": [],
  "zeroconf": [],
  "homekit": {},
  "dependencies": [],
  "loggers": ["custom_components.jvc_projectors"],
  "codeowners": [
    "@iloveicedgreentea"
  ],
  "iot_class": "local_polling",
  "version": "4.2.1"
}
```
This doesn't make sense though as it says 4.2.1....but when I got to HACS I see 4.2.9?  
[remote.txt](https://github.com/iloveicedgreentea/jvc_homeassistant/files/14729716/remote.txt)

(changed extension to .txt as .py isn't supported)

**Comment by iloveicedgreentea** [comment] 2024-03-23 01:18
Yeah I just never updated that field it

Thats the right code. Let me know if the issue comes back and if so, what you were doing around that time. I haven't been able to replicate any issues so far

**Comment by iscofield** [comment] 2024-03-23 01:38
Hopefully it was just a fluke! Really appreciate your help and for creating this!

**Comment by mrpedaling** [comment] 2024-03-23 02:22
Hi, I've been following along as I had the same issues (nz7 fwiw) namely the deadlocking and odd attributes and log errors. 4.2.9 fixed all things here as well as far as I can tell. I did notice that after the hacs update and HA restart it showed connection status/signal status false... until the next power on of the projector. Then everything looked good. 

The only thing I've noticed is the low latency attribute doesn't seem to be accurate compared to what the menus in the projector say. Feels minor, and I don't want to pull focus away from the OP's topic or this comment's point of "this version seems to fix things here afaict". 

Carry on. Thanks for the code, improvements and maintenance!

**Comment by roninf** [comment] 2024-03-23 10:41
> While the projector is off, the connection status is false. If I turn on the projector via the IR remote or my Harmony, it stays as false and never switches. If I turn on the projector via the plugin, then it will say true and everything will populate (after it sits for a bit, then says the remote is off, then comes back).
> 
> Will grab the debugs later today/tonight and send them over.

Exactly the same for me.

**Comment by roninf** [comment] 2024-03-23 10:44
> The only thing I've noticed is the low latency attribute doesn't seem to be accurate compared to what the menus in the projector say.

I recognized that as well, i cant turn on low latency as well.

**Comment by roninf** [comment] 2024-03-23 10:52
I have had the following error last nigh i don`t know if its related:

```
Logger: custom_components.jvc_projectors.remote
Quelle: custom_components/jvc_projectors/remote.py:219
Integration: JVC Projector ([Dokumentation](https://github.com/iloveicedgreentea/jvc_homeassistant))
Erstmals aufgetreten: 22. März 2024 um 23:52:24 (1 Vorkommnisse)
Zuletzt protokolliert: 22. März 2024 um 23:52:24
Unhandled exception in handle_queue: b'PW' is not a valid InputLevel
```

This morning i recognized the integration showing the NZ8 on while it was definitely off.

**Comment by iloveicedgreentea** [comment] 2024-04-08 00:59
Can you try 4.4.03 please

**Comment by iloveicedgreentea** [comment] 2024-04-08 15:27
> I will check it out as soon as possible.

4.4.04 now, or whatever the latest is at the time. I am actively developing stuff

**Comment by roninf** [comment] 2024-04-08 17:52
Looks good so far. (4.4.04) Powered on immediately and showing the states as well as it seems. I will go on testing.

**Comment by iloveicedgreentea** [comment] 2024-04-08 19:21
4.4.05 fixes a potential issue with queues

**Comment by roninf** [comment] 2024-04-08 19:42
Must correct myself, just turned off the projector using the remote. The integration still shows it running. Will do further testing tomorrow.

**Comment by iloveicedgreentea** [comment] 2024-04-08 19:43
yeah the latest version should fix that

**Comment by roninf** [comment] 2024-04-08 19:48
I am on 4.4.0.4. Just tried to turn off the integration but it stays on no matter how often i press the switch off button of the integration.

**Comment by iloveicedgreentea** [comment] 2024-04-08 19:49
4.4.05 is the latest version as of now

**Comment by roninf** [comment] 2024-04-09 15:38
I was able turn on and off the Projector ones using the integration. A second time it did just nothing -  unfortunately.

**Comment by roninf** [comment] 2024-04-09 15:58
Reloading the integration now shows the correct values.

**Comment by roninf** [comment] 2024-04-09 16:38
Next short update. After a while the integration switches to show offline again while the projector is on.

**Comment by iloveicedgreentea** [comment] 2024-04-09 22:29
Is this on the latest version? There have been newer ones since then that issue should have been fixed already. If you encounter issues please send me debug logs because I dont encounter these issues with my setup. Only difference I see is I have an nz7, you have nz8, and another person reporting issues has nz9. I wonder if theres something different with the nz7 model because otherwise, I have no idea why some users have issues

But anyway try the latest version and let me know

**Comment by mrpedaling** [comment] 2024-04-09 22:37
I've got an nz7, I'll get the latest version and report back after tonight's watching.

**Comment by iloveicedgreentea** [comment] 2024-04-19 15:22
I was finally able to replicate the issues. It was a result of sending commands and shifting the queue position. 


v4.4.08 fixes it for me

**Comment by iloveicedgreentea** [comment] 2024-05-31 19:09
I rewrote this with sync code primarily because the JVC protocol is highly fragile and synchronous and I was fighting an uphill battle doing it async. I added the new features like laser value (0-100) and other stuff, let me know if something is missing.

Please try the latest 3.7.x beta in HACS which is now v3.7.34

Keep in mind this removes config flow so you will need to add it to your configuration.yaml again (see readme)

The alternative is to use the integration that is in the official repo but that is lacking a lot of features. 

I am focusing my efforts on writing a home assistant like thing focused on theaters and theater devices

Let me know if this version has any major issues. I have tested it for over a week now and it has been fine for me.

**Comment by anevard** [comment] 2024-06-01 17:43
Running 4.2.1.  I am having issues with the projector being turned Off by IR and it showing as On.  It is resolved if I restart HA.

Also is it possible to test for the standby state etc.  Seems the power_state is only true or false.

I am a noob with HA so when I tried to switch to this version from 4.2.1 it just crashed HA and none of my custom_components would load.  Back up with 4.2.1 but any guidance would be appreciated.

**Comment by iloveicedgreentea** [comment] 2024-06-02 22:44
>EDIT: Crash resolved, running 3.7.3 ?.4 But it won't load entity.

You will need to add a new one via config yaml or remove the old one and change the new name to match the old one

**Comment by anevard** [comment] 2024-06-23 14:11
Unfortunately I am not able to get the beta working.  I don’t seem to be able to correctly understand how to add it to the configuration.yaml as it never works.  

The 4.2.1 version works but regularly loses connection with the projector and all sensors stay stuck in their last state until the integration is reloaded.  Even upon reload I see pipe errors. 

Here is an error log before the reload if that helps in any way.  Please excuse this if it has already been dealt with in the beta rewrites.

``` 
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:941 
First occurred: June 22, 2024 at 11:48:31 PM (1179 occurrences) 
Last logged: 9:37:32 AM

Update for remote.nx7 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 160, in _do_command
    await self.writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 380, in drain
    raise exc
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1065, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1289, in async_device_update
    await self.async_update()
  File "/config/custom_components/jvc_projectors/remote.py", line 351, in async_update
    self._state = await self.jvc_client.is_on()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/jvc_projector.py", line 517, in is_on
    return await self._get_power_state() in pw_status
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/jvc_projector.py", line 510, in _get_power_state
    return await self._get_attribute("power_status", ACKs.power_ack, PowerStates)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/jvc_projector.py", line 314, in _get_attribute
    state, res = await self.commander.do_reference_op(command, ack)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 268, in do_reference_op
    msg, success = await self.send_command(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 82, in send_command
    return await self._do_command(send_command, ack, command_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jvc_projector/command_runner.py", line 164, in _do_command
    raise ConnectionClosedError(err) from err
jvc_projector.error_classes.ConnectionClosedError: [Errno 32] Broken pipe

```

**Comment by iloveicedgreentea** [comment] 2024-06-23 16:44
>Unfortunately I am not able to get the beta working. I don’t seem to be able to correctly understand how to add it to the configuration.yaml as it never works.

Install the file editor add on

Install the latest beta from HACS & restart HA

In configuration.yaml add this

```yaml
remote:
  - platform: jvc_projectors
    name: nz7 (or whatever name you want)
    password: (your password you set if NZ model)
    host: (your ip address of the unit)
```

Disable the existing integration (don't delete yet)

Restart HA

You should see remote.nz7 now

If everything works, you can delete the existing integration and rename entities in your automations if needed

Yes those issues are fixed in the latest beta. I probably won't add config flow to this because there is already an official integration but maybe one day if I have free time.

**Comment by iloveicedgreentea** [comment] 2024-06-23 16:44
I am going to close this issue if you have further issues please open a new one. I will probably release the latest beta as official soon.

**Closed by iloveicedgreentea** 2024-06-23 16:44 UTC
